### ISSUE TITLE
Error and warning updates

### ISSUE THREAD

**Issue by joeflack4** [PMA-2020/ppp-web#19]
# Issue Summary
1. Warnings should be a yellow flash message. And should not stop conversion.
2. OdkException by ppp.run() should not convert. Red flash message. No stack trace.
3. All other Exception by ppp.run() should not convert. Red flash message. Include stack trace.

---

# 1. Warnings
## Description
Warnings should not stop conversion.

The ppp core and CLI (http://github.com/PMA-2020/ppp) creates warnings and errors. Errors are exceptions that are raised. Warnings are printed to `stderr`, but do not raise an exception. Currently, ppp-web does not convert a file if it sees a message in `stderr`. We should change that. It should only stop conversion if there is an `Exception`

## Desired/expected behavior 
If a warning is shown in Stderr, conversion should continue, and the warning message should appear in the browser.

![example warning](https://user-images.githubusercontent.com/13045020/45764539-edc60680-bc00-11e8-8d80-3c5f8999d77e.png)

## Actual behavior
PPP-web thinks that it is an error, and cancels conversion. Message displayed also looks like an error.

![should be warning not error](https://user-images.githubusercontent.com/13045020/45764570-fe767c80-bc00-11e8-880b-a471b1df271b.png)

## Additional information
I don't know why, but right now ppp.pma2020.org and ppp-staging.pma2020.org _can_ convert the attached file. There isn't even an error message. However, if you clone this repo and run locally, and try to convert his file, you will see an error.

**Where is the logic that handles errors/warnings located?**
I think it will help to look at `views.py`, around line `77`:
```python
# if ppp.ppp tool wrote something to stderr, we should show it to user
        if stderr:
            flash("STDERR:\n{}".format(stderr), "error")
            return redirect(url_for('index'))
```

**Attachments**
1. [warnings.xlsx.zip](https://github.com/PMA-2020/ppp-web/files/2397753/warnings.xlsx.zip)

# 2. Exception handling for`OdkException`
Remove stack trace from error message.

Here is an example  
[OdkChoicesError.xlsx.zip](https://github.com/PMA-2020/ppp-web/files/2479274/OdkChoicesError.xlsx.zip)

Converting this file should make this kind of error message:
![odkchoiceserror](https://user-images.githubusercontent.com/13045020/46958947-e7dd0d00-d068-11e8-848e-afd58a153910.png)

# 3. Exception handling for any other exception that is not `OdkException`
For these exceptions, please show the stacktrace.

Here is an example  
[UnhandledException.xlsx.zip](https://github.com/PMA-2020/ppp-web/files/2479270/UnhandledException.xlsx.zip)

Converting this file should make this kind of error message:
![unhandledexception](https://user-images.githubusercontent.com/13045020/46959053-2377d700-d069-11e8-8b83-25b5da26bb6e.png)

---

**Task list**
- [x] 1. Warnings - warnings should not stop conversion.
- [x] 2. `OdkException` - do not show stack trace
- [x] 3. All other `Exception` - show stack trace

**Comment by joeflack4** [comment]
@bciar Everything looks like it works now to me!
